name: CI

on: 
  push: 
    branches: 
      - master
  pull_request:
    branches:
      - master

env:
  flutter-version: "2.10.3"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: flutter analyze
      - run: flutter format . --set-exit-if-changed
